---
- name: Copy Filebeat configuration.
  ansible.builtin.template:
    src: "{{ filebeat_template }}"
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: Restart filebeat

- name: Ensure Filebeat SSL directories exist.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - filebeat_ssl_certs_dir
    - filebeat_ssl_private_dir
  when: filebeat_ssl_key_file | length > 0

- name: Copy SSL key and cert for filebeat.
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ item.dir }}/{{ item.file | basename }}"
    mode: 0644
  with_items:
    - dir: "{{ filebeat_ssl_private_dir }}"
      file: "{{ filebeat_ssl_key_file }}"
    - dir: "{{ filebeat_ssl_certs_dir }}"
      file: "{{ filebeat_ssl_certificate_file }}"
  notify: Restart filebeat
  when:
    - filebeat_ssl_copy_files | bool
    - filebeat_ssl_key_file | length > 0
    - filebeat_ssl_certificate_file | length > 0

# - name: Ensure filebeat can read system's private key
