---
- name: Ensure required dependencies are present.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Elasticsearch apt key.
  ansible.builtin.get_url:
    url: "{{ filebeat_elastic_apt_gpg_key }}"
    dest: /etc/apt/trusted.gpg.d/filebeat.asc
    mode: '0644'
    force: true
  register: add_repository_key
  ignore_errors: "{{ filebeat_apt_ignore_key_error }}"
  when: filebeat_add_repo | bool

- name: Add Filebeat repository.
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/filebeat.asc] https://artifacts.elastic.co/packages/{{ filebeat_version }}/apt stable main'
    state: present
    update_cache: true
